### ISSUE TITLE
关于初始化

### ISSUE THREAD

**Issue by WenmuZhou** [GuoQuanhao/Tiny-Face-Paddle#1]
请问为何要用指定的参数来初始化，而不用随机初始化
![image](https://user-images.githubusercontent.com/12406017/147209804-51d4fa83-ace1-47ad-91e6-75a6764d3043.png)

**Comment by GuoQuanhao** [comment]
paddle随机初始化bias为0，使用ParamAttr参数后weight初始化方式为Xavier，使用默认初始化loss_cls初始loss大约在6左右，使用initial.pdparams后，loss_cls初始loss大约在2左右，默认初始化将训练一倍的epochs才能得到同样的效果。

目前新增initializer.py，完美复刻了torch的初始化方法，在https://github.com/GuoQuanhao/Tiny-Face-Paddle/blob/818882889aba5e5a6afd61e1c5a9e06620b2c347/models/model.py#L31

中新增了权重初始化操作，目前loss_cls初始loss大约在2左右，并通过十多个左右steps则能降至1以内。可以从readme中截取了初始训练保存的训练日志
